version: '3.7'
services:
  uniswap:
    extends:
      file: docker-compose.base.yml
      service: uzh-blockchain-data-analysis-base
    command: npm run uniswap:dev:docker
    ports:
      - '4003:4003'
    depends_on:
      - collection_db
    env_file:
      - ./apps/uniswap/.env
    profiles: ["uniswap", "all"]

volumes:
  postgres-volume:
  uzh-blockchain-data-analysis-node-modules: null
  nx-cache: null