version: '3'

services:
  uzh-blockchain-data-analysis-base:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./:/app
      - uzh-blockchain-data-analysis-node-modules:/app/node_modules
    
  collection-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    user: "${DATA_UID}:${DATA_GID}"
    group_add:
      - ${DATA_GID}
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    env_file:
      - .env
    volumes:
      - ${DATA_DIR}/postgresql-data:/var/lib/postgresql/data