const GLOBAL_PREFIX = "http://localhost:4000";

const UNISWAP_ROUTE = `${GLOBAL_PREFIX}/api/uniswap`;

const POOL_ROUTE = `${UNISWAP_ROUTE}/pool`;

const SWAP_ROUTE = `${UNISWAP_ROUTE}/swap`;

const TOTAL_COUNT_ROUTE = `${POOL_ROUTE}/count`;

const TOKENS_WITH_MOST_POOLS_ROUTE = `${POOL_ROUTE}/top-tokens`;

const POOL_COUNT_BY_DATE = `${POOL_ROUTE}/count-by-date`;

const ALL_SWAPS_ROUTE = `${SWAP_ROUTE}/all`;

const POOL_SWAP_COUNT = `${SWAP_ROUTE}/pool-swap-count`;

const TOP_ACTIVE_POOLS_ROUTE = `${SWAP_ROUTE}/active-pools`;

const TOP_ACTIVE_ADDRESSES_ROUTE = `${SWAP_ROUTE}/active-addresses`;

const POOL_PRICE_AND_VOLUME_ROUTE = `${SWAP_ROUTE}/daily-price`;

const NEW_USERS_BY_DATE_RANGE = `${SWAP_ROUTE}/new-users`;

const POOL_PRICE_BY_ADDRESS_DATE_RANGE = `${SWAP_ROUTE}/price-by-pool`;

const PAIR_PRICE_BY_ADDRESS_DATE_RANGE = `${SWAP_ROUTE}/price-by-pair`;

const DISTINCT_USERS_BY_DATE_RANGE = `${SWAP_ROUTE}/distinct-users`;

const LIQUIDITY_ROUTE = `${UNISWAP_ROUTE}/liquidity`;

const POOL_FLOW_ROUTE = `${LIQUIDITY_ROUTE}/pool-flow`;

const POOL_TOTAL_FLOW_ROUTE = `${LIQUIDITY_ROUTE}/pool-total-flow`;

export const ROUTES = {
  TOTAL_COUNT_ROUTE,
  TOKENS_WITH_MOST_POOLS_ROUTE,
  PAIR_PRICE_BY_ADDRESS_DATE_RANGE,
  ALL_SWAPS_ROUTE,
  POOL_COUNT_BY_DATE,
  POOL_PRICE_BY_ADDRESS_DATE_RANGE,
  POOL_SWAP_COUNT,
  NEW_USERS_BY_DATE_RANGE,
  TOP_ACTIVE_POOLS_ROUTE,
  TOP_ACTIVE_ADDRESSES_ROUTE,
  POOL_PRICE_AND_VOLUME_ROUTE,
  DISTINCT_USERS_BY_DATE_RANGE,
  POOL_FLOW_ROUTE,
  POOL_TOTAL_FLOW_ROUTE,
};
